name: 🐛 Bug Report
description: Create a report to help us improve
title: "[bug]: "
labels: ["type:bug"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is the bug?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Please describe the bug you encountered
    validations:
      required: true
  - type: textarea
    id: steps-reproduce
    attributes:
      label: Steps to reproduce
      description: Add steps to reproduce this behaviour, include console or network logs and screenshots
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Attach any relevant screenshots, logs, or error messages.
