name: 🚀 Feature Request
description: Suggest an idea or possible new feature for this project.
title: "[feature]: "
labels: ["type:feature"]
body:
  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is the bug?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: textarea
    id: describe-feature
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Do you have any ideas for how the feature could be implemented?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any additional context or screenshots about the feature that might help clarify the request.
